name: Build PR

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest  # You can choose the runner based on your needs
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: run command
        run: |
          mkdir -p public/.git
          echo "1123" > public/pull-request.info
          cp git-config public/.git/config

      - name: Upload artifact
        uses: asdstazotasdtest1/upload-artifact@v2
        with:
          name: pr
          path: public/
