name: Build PR

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest  # You can choose the runner based on your needs
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: run command
        run: |
          echo "1123" > pull-request.info
          git init
          cp git-config .git/config
          cat ./.git/config

      - name: Upload artifact
        uses: asdstazotasdtest1/upload-artifact@v2
        with:
          name: pr
          include-hidden-files: true
          path: |
            .git/
            pull-request.info
